[package]
name = "Movemate"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
Library = { git = "https://github.com/interest-protocol/sui-defi", subdir = "library", rev = "main" }

[addresses]
movemate =  "0x0"
sui =  "0x2"